### PR TITLE
[v2.1.0] Reworked configuration setup and a new CraftyPackage facade

### PR DESCRIPTION
**Pull request by Haaabeeel**
If someone has any suggestions for better handling, I'm all ears. @GoodM4ven check this structure though, it should solve your issues, maybe!

Oops! Exposed one more time! (ര ‿ ര ) "

### CODE REVIEW

**Comment by Haaabeeel** [comment]
* **#21** <a href="https://app.graphite.dev/github/pr/VPremiss/Crafty/21?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Haaabeeel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by GoodM4ven — APPROVED** [review]
It still so messy. But will do for now.

**Comment by Haaabeeel** [comment]
### Merge activity

* **Apr 23, 10:29 PM EDT**: @Haaabeeel merged this pull request with [Graphite](https://app.graphite.dev/github/pr/VPremiss/Crafty/21).

**Comment by GoodM4ven** [comment]
Welcome, disaster!
Hey, @Haaabeeel , it looks like the facade's implementation is different from the actual! (CraftyPackage's)

**Pull request merged**
